const list = [
    {
      id: 1,
      title: "Rajestani-Thali",
      description: "breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 89,
      img: "https://st2.depositphotos.com/5653638/11520/i/950/depositphotos_115205260-stock-photo-indian-thali-indian-food-thali.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Dosa",
      description: "evening Lorem ipsum dolor sit amet consectetur adipisicing als elit. Blanditiis.",
      price: 98,
      img: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/l4h50obbhvtdmp2lnrud",
      amount: 1,
    },
    {
      id: 3,
      title: "Orissa Thali",
      description: "breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit.  Blanditiis",
      price: 43,
      img: "https://st2.depositphotos.com/5653638/11520/i/950/depositphotos_115207682-stock-photo-indian-thali-indian-food-thali.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Fish-Thali",
      description: "lunch Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 100,
      img: "https://st3.depositphotos.com/5653638/15189/i/1600/depositphotos_151892632-stock-photo-fish-biryani-or-fish-rice.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "My First 1000 Words",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 149,
      img: "https://st2.depositphotos.com/5653638/11511/i/950/depositphotos_115111216-stock-photo-maharashtrian-or-marathi-food-platter.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Bihari-Thali",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 135,
      img: "https://st2.depositphotos.com/28132718/44463/i/1600/depositphotos_444631720-stock-photo-indiamakki-roti-sarson-saag-onion.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Sweet-Thali",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 693,
      img: "https://st2.depositphotos.com/28132718/44072/i/1600/depositphotos_440726924-stock-photo-popular-sweet-dish-jalebi-searved.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Breakfast Thali",
      description: "Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 289,
      img: "https://st2.depositphotos.com/4940251/44307/i/1600/depositphotos_443079708-stock-photo-full-breakfast-plate-black-surface.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Traditional Thali ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 80,
      img: "https://st4.depositphotos.com/10807198/20646/i/1600/depositphotos_206462600-stock-photo-mongolian-traditional-food-table.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Chicken Thali",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 86,
      img: "https://st4.depositphotos.com/2673591/19695/i/1600/depositphotos_196957500-stock-photo-indonesian-cuisine-opor-ayam-chicken.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Dessert-combo",
      description: "dinner Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 120,
      img: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/flfqio0uxpsfsdvaaejb",
      amount: 1,
    },
    {
      id: 12,
      title: "Non-Veg Thali",
      description: "dinner Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis.",
      price: 157,
      img: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ime81lssy8ozalrontlq",
      amount: 1,
    },
  ];
  
  export default list;